-- MySQL Script generated by MySQL Workbench
-- Tue Oct 29 18:44:03 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema FTDB
-- -----------------------------------------------------
DROP DATABASE IF EXISTS FinancialTrackingToolDB;
CREATE DATABASE FinancialTrackingToolDB;
USE FinancialTrackingToolDB;
-- -----------------------------------------------------
-- Table `PaymentCategory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PaymentCategory` ;

CREATE TABLE IF NOT EXISTS `PaymentCategory` (
  `PaymentCategory_id` INT NOT NULL,
  `type_name` VARCHAR(45) NOT NULL,
  `color_code` VARCHAR(45) NULL,
  PRIMARY KEY (`PaymentCategory_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Payment Transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Payment Transaction` ;

CREATE TABLE IF NOT EXISTS `Payment Transaction` (
  `Payment_Transaction_id` INT NOT NULL,
  `amount` INT NOT NULL,
  `store_name` VARCHAR(45) NOT NULL,
  `date` DATE NOT NULL,
  `note` VARCHAR(45) NULL,
  `PaymentCategory_id` INT NOT NULL,
  `Expense_id` INT,
  PRIMARY KEY (`Payment_Transaction_id`, `PaymentCategory_id`),
  INDEX `fk_Payment Transaction_PaymentCategory1_idx` (`PaymentCategory_id` ASC) VISIBLE,
  INDEX `fk_Payment Transaction_Expense_idx` (`Expense_id` ASC) VISIBLE,
  CONSTRAINT `fk_Payment Transaction_PaymentCategory1`
    FOREIGN KEY (`PaymentCategory_id`)
    REFERENCES `PaymentCategory` (`PaymentCategory_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Payment Transaction_Expense`
    FOREIGN KEY (`Expense_id`)
    REFERENCES `Expense` (`Expense_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE
    )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Expense`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Expense` ;

CREATE TABLE IF NOT EXISTS `Expense` (
  `Expense_id` INT NOT NULL,
  PRIMARY KEY (`Expense_id`)
  )
  
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EarningCategory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EarningCategory` ;

CREATE TABLE IF NOT EXISTS `EarningCategory` (
  `EarningCategory_id` INT NOT NULL,
  `type_name` VARCHAR(45) NOT NULL,
  `color_code` VARCHAR(45) NULL,
  PRIMARY KEY (`EarningCategory_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IncomeTransaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IncomeTransaction` ;

CREATE TABLE IF NOT EXISTS `IncomeTransaction` (
  `Income_Transaction_id` INT NOT NULL,
  `amount` INT NOT NULL,
  `source_name` VARCHAR(45) NOT NULL,
  `date` DATE NOT NULL,
  `note` VARCHAR(45) NULL,
  `EarningCategory_EarningCategory_id` INT NOT NULL,
  `Income_id` INT,
  PRIMARY KEY (`Income_Transaction_id`, `EarningCategory_EarningCategory_id`),
  INDEX `fk_IncomeTransaction_EarningCategory1_idx` (`EarningCategory_EarningCategory_id` ASC) VISIBLE,
  INDEX `fk_IncomeTransaction_Income_idx` (`Income_id` ASC) VISIBLE,
  CONSTRAINT `fk_IncomeTransaction_EarningCategory1`
    FOREIGN KEY (`EarningCategory_EarningCategory_id`)
    REFERENCES `EarningCategory` (`EarningCategory_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_IncomeTransaction_Income_idx`
    FOREIGN KEY (`Income_id`)
    REFERENCES `Income` (`Income_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Income`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Income` ;

CREATE TABLE IF NOT EXISTS `Income` (
  `Income_id` INT NOT NULL,
  PRIMARY KEY (`Income_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Budget`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Budget` ;

CREATE TABLE IF NOT EXISTS `Budget` (
  `Budget_id` INT NOT NULL,
  `amount` INT NOT NULL,
  `PaymentCategory_id` INT NOT NULL,
  PRIMARY KEY (`Budget_id`, `PaymentCategory_id`),
  INDEX `fk_Budget_PaymentCategory1_idx` (`PaymentCategory_id` ASC) VISIBLE,
  CONSTRAINT `fk_Budget_PaymentCategory1`
    FOREIGN KEY (`PaymentCategory_id`)
    REFERENCES `PaymentCategory` (`PaymentCategory_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Saving`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Saving` ;

CREATE TABLE IF NOT EXISTS `Saving` (
  `Saving_id` INT NOT NULL,
  `amount` INT NOT NULL,
  `target_goal_note` VARCHAR(45) NULL,
  PRIMARY KEY (`Saving_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Account` ;

CREATE TABLE IF NOT EXISTS `Account` (
  `account_id` INT NOT NULL,
  `creation_date` TIMESTAMP NULL,
  `Role_type` VARBINARY(15) NOT NULL,
  `Expense_id` INT NOT NULL,
  `income_id` INT NOT NULL,
  `Budget_id` INT NOT NULL,
  `Saving_id` INT NOT NULL,
  PRIMARY KEY (`account_id`, `income_id`, `Expense_id`, `Budget_id`, `Saving_id`),
  INDEX `fk_Account_Expense1_idx` (`Expense_id` ASC) VISIBLE,
  INDEX `fk_Account_Income1_idx` (`income_id` ASC) VISIBLE,
  INDEX `fk_Account_Budget1_idx` (`Budget_id` ASC) VISIBLE,
  INDEX `fk_Account_Saving1_idx` (`Saving_id` ASC) VISIBLE,
  CONSTRAINT `fk_Account_Expense1`
    FOREIGN KEY (`Expense_id`)
    REFERENCES `Expense` (`Expense_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Account_Income1`
    FOREIGN KEY (`income_id`)
    REFERENCES `Income` (`income_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Account_Budget1`
    FOREIGN KEY (`Budget_id`)
    REFERENCES `Budget` (`Budget_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Account_Saving1`
    FOREIGN KEY (`Saving_id`)
    REFERENCES `Saving` (`Saving_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `User` ;

CREATE TABLE IF NOT EXISTS `User` (
  `user_id` INT NOT NULL,
  `user_name` VARCHAR(45) NOT NULL,
  `user_password` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_password_UNIQUE` (`user_password` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RegisteredUser`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RegisteredUser` ;

CREATE TABLE IF NOT EXISTS `RegisteredUser` (
  `email` VARCHAR(45) NULL,
  `user_id` INT NOT NULL,
  `account_id` INT NOT NULL,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  PRIMARY KEY (`user_id`, `account_id`),
  INDEX `fk_RegisteredUser_Account1_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `fk_RegisteredUser_User`
    FOREIGN KEY (`user_id`)
    REFERENCES `User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RegisteredUser_Account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `Account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Chart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Chart` ;

CREATE TABLE IF NOT EXISTS `Chart` (
  `Chart_id` INT NOT NULL,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`Chart_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VisualizePreference`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VisualizePreference` ;

CREATE TABLE IF NOT EXISTS `VisualizePreference` (
  `Visualize_Preference_id` INT NOT NULL auto_increment,
  `start_date` DATE NULL,
  `end_date` DATE NULL,
  PRIMARY KEY (`Visualize_Preference_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Dashboard`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Dashboard` ;

CREATE TABLE IF NOT EXISTS `Dashboard` (
  `Dashboard_id` INT NOT NULL,
  `account_id` INT NOT NULL,
  PRIMARY KEY (`Dashboard_id`, `account_id`),
  INDEX `fk_Dashboard_Account1_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `fk_Dashboard_Account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `Account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Visualize`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Visualize` ;

CREATE TABLE IF NOT EXISTS `Visualize` (
  `Visualize_id` INT NOT NULL,
  `Dashboard_id` INT NOT NULL,
  `Visualize_Preference_id` INT NOT NULL,
  `Chart_id` INT NOT NULL,
  PRIMARY KEY (`Visualize_id`),
  INDEX `fk_Visualize_VisualizePreference1_idx` (`Visualize_Preference_id` ASC) VISIBLE,
  INDEX `fk_Visualize_Chart1_idx` (`Chart_id` ASC) VISIBLE,
  INDEX `fk_Visualize_Dashboard1_idx` (`Dashboard_id` ASC) VISIBLE,
  CONSTRAINT `fk_Visualize_VisualizePreference1`
    FOREIGN KEY (`Visualize_Preference_id`)
    REFERENCES `VisualizePreference` (`Visualize_Preference_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Visualize_Chart1`
    FOREIGN KEY (`Chart_id`)
    REFERENCES `Chart` (`Chart_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Visualize_Dashboard1`
    FOREIGN KEY (`Dashboard_id`)
    REFERENCES `Dashboard` (`Dashboard_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HistoricalComparingPreference`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HistoricalComparingPreference` ;

CREATE TABLE IF NOT EXISTS `HistoricalComparingPreference` (
  `HistoricalComparingPreference_id` INT NOT NULL,
  `start_date` DATE NULL,
  `end_date` DATE NULL,
  PRIMARY KEY (`HistoricalComparingPreference_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HistoricalComparing`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HistoricalComparing` ;

CREATE TABLE IF NOT EXISTS `HistoricalComparing` (
  `HistoricalComparing_id` INT NOT NULL,
  `HistoricalComparingPreference_id` INT NOT NULL,
  `Dashboard_id` INT NOT NULL,
  PRIMARY KEY (`HistoricalComparing_id`),
  INDEX `fk_HistoricalComparing_HistoricalComparingPreference1_idx` (`HistoricalComparingPreference_id` ASC) VISIBLE,
  INDEX `fk_HistoricalComparing_Dashboard1_idx` (`Dashboard_id` ASC) VISIBLE,
  CONSTRAINT `fk_HistoricalComparing_HistoricalComparingPreference1`
    FOREIGN KEY (`HistoricalComparingPreference_id`)
    REFERENCES `HistoricalComparingPreference` (`HistoricalComparingPreference_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HistoricalComparing_Dashboard1`
    FOREIGN KEY (`Dashboard_id`)
    REFERENCES `Dashboard` (`Dashboard_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BudgetComparingPreference`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BudgetComparingPreference` ;

CREATE TABLE IF NOT EXISTS `BudgetComparingPreference` (
  `BudgetComparingPreference_id` INT NOT NULL,
  `start_date` DATE NULL,
  `end_date` DATE NULL,
  PRIMARY KEY (`BudgetComparingPreference_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BudgetComparing`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BudgetComparing` ;

CREATE TABLE IF NOT EXISTS `BudgetComparing` (
  `BudgetComparing_id` INT NOT NULL,
  `BudgetComparingPreference_id` INT NOT NULL,
  `Dashboard_id` INT NOT NULL,
  PRIMARY KEY (`BudgetComparing_id`),
  INDEX `fk_BudgetComparing_BudgetComparingPreference1_idx` (`BudgetComparingPreference_id` ASC) VISIBLE,
  INDEX `fk_BudgetComparing_Dashboard1_idx` (`Dashboard_id` ASC) VISIBLE,
  CONSTRAINT `fk_BudgetComparing_BudgetComparingPreference1`
    FOREIGN KEY (`BudgetComparingPreference_id`)
    REFERENCES `BudgetComparingPreference` (`BudgetComparingPreference_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BudgetComparing_Dashboard1`
    FOREIGN KEY (`Dashboard_id`)
    REFERENCES `Dashboard` (`Dashboard_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Notification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Notification` ;

CREATE TABLE IF NOT EXISTS `Notification` (
  `Notification_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `alert_message` VARCHAR(45) NULL,
  PRIMARY KEY (`Notification_id`, `user_id`),
  INDEX `fk_Notification_RegisteredUser1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_Notification_RegisteredUser1`
    FOREIGN KEY (`user_id`)
    REFERENCES `RegisteredUser` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Report`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Report` ;

CREATE TABLE IF NOT EXISTS `Report` (
  `Report_id` INT NOT NULL,
  `report_date` DATETIME NOT NULL,
  `account_id` INT NOT NULL,
  `month` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Report_id`, `account_id`),
  INDEX `fk_Report_Account1_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `fk_Report_Account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `Account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `summarize`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `summarize` ;

CREATE TABLE IF NOT EXISTS `summarize` (
  `Report_id` INT NOT NULL,
  `summary_id` INT NOT NULL,
  PRIMARY KEY (`Report_id`, `summary_id`),
  INDEX `fk_summarize_Report2_idx` (`summary_id` ASC) VISIBLE,
  CONSTRAINT `fk_summarize_Report1`
    FOREIGN KEY (`Report_id`)
    REFERENCES `Report` (`Report_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_summarize_Report2`
    FOREIGN KEY (`summary_id`)
    REFERENCES `Report` (`Report_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
